[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
broadcast = 'records'
fs_permissions = [ {access = "read-write", path = "./"} ]
optimizer = true
optimizer_runs = 999999
solc_version = "0.8.23"
via-ir = true
remappings = [
    '@base-contracts/=lib/base-contracts',
    'basenames/=lib/basenames/src/'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config